import NewFlashcard from './NewFlashcard.js';
import { useState, useRef } from 'react';
import { requestCreateSet, requestAddNewFlashcard } from '../../requests.js';
import axios from 'axios';

export default function CreateFlashcardSet({requestStudySets, setRequestStudySets}) {
    const [cards, updateCards] = useState([]);
    // we use this id LOCALLY for displaying, deleting, & updating the created cards - the card's ID on the backend is generated by the server
    const nextCardIdRef = useRef(0);
    const [setTitle, updateSetTitle] = useState("");

    // this adds a blank card to the newly created set
    function addCard() { 
        updateCards([...cards, {id: nextCardIdRef.current, prompt: "", response: "", fileJSON: {file: null, isPrompt: null}, userResponseType: "text"}]);
        nextCardIdRef.current += 1;
    }
    // this removes the card with the specified id from the list of cards being added to the new stud yset
    function removeCard(removedId) {
        updateCards(cards.filter(card => card.id !== removedId)); // finding and removing the card with the specified id
    }
    // this updates a flashcard with the provided ID and sets its fields based on the passed parameters
    function updateCard(newPrompt, newResponse, cardId, newFileJSON, newUserResponseType) { // this is used to update cards when the user edits a prompt or response
        updateCards(cards.map(card => 
            card.id === cardId ? {id: cardId, prompt: newPrompt, response: newResponse, 
                                  fileJSON: newFileJSON, userResponseType: newUserResponseType}: card
        ));
    }
    // this function makes a POST request to the API to save our newly created study set
    function saveSet() {
        // first need to validate that all the cards have a valid state - non-empty prompt and response, indicate whether file is for a prompt or response
        if (!validateCards(cards) || setTitle === "") {
            alert("Please ensure all entered data is valid"); // there should be more graceful error handling than this
            return;

            // 1. Using alert may be intrusive, can test both with and without
            // 2. Clearly indicate which fields are invalid & why
            // (should do this later, for now just get base functionality up)

        }

        Promise.all( // we first need to create the set we're going to add our flashcards to
            [requestCreateSet(setTitle)]
        ).then((response) => { // upon getting our response we get the ID of the created set so we can add cards to that id
            const createdSetId = response[0].data._id;
            Promise.all(cards.map((card) => {
                return requestAddNewFlashcard(createdSetId, card);
            }))
        }).then(() => { // we've successfully added all cards!
            setRequestStudySets(!requestStudySets); // attempting to save refreshes the application's stored study sets
            alert("Set created successfully!"); 
            window.location.href = "http://localhost:3000"; // redirecting to the home page only on success
        }).catch((error) => {
            console.log(error);
        });
        
    }

    // this contains the JSX for the interface to allow users to modify the flashcards that will be added to the new set
    let cardList = cards.map(card => (
        <li key={card.id} className="new-flashcard"> 
            <NewFlashcard
                card={card}
                removeCard={removeCard}
                updateCard={updateCard}
            />
        </li>
    ));
    
    return <div className="new-flashcard-set">
        <button className="add-flashcard-button" onClick={addCard}>Add Card</button>
        <button className="save-button" onClick={saveSet}>Save</button> <br/>
        <label htmlFor="set-title">Set Title:</label>
        <input type="text" name="set-title" id="set-title" value={setTitle} 
            onChange={(e) => updateSetTitle(e.target.value)}></input>
        <ul className="new-card-list">
            {cardList}
        </ul>
    </div>
}

// this method validates the provided array of cards so they can be stored on the server
function validateCards(cards) {
    if (cards.length === 0) { // sets should initially contain at least 1 card, fewer than that doesn't make sense
        return false;
    }
    for (let i = 0; i < cards.length; i++) {
        const currentCard = cards[i];
        // NOTE: not clear if the prompt and/or response should be allowed to be empty if there is a file displayed as part of the prompt or response
        if (currentCard.prompt === "" || currentCard.response === "") { // prompt and response can't be empty
            return false;
        }
        if (currentCard.fileJSON.file !== null && currentCard.fileJSON.isPrompt === null) { // user must indicate where a file should be displayed as part of a card 
            return false;
        }
    }
    return true; // all cards are valid if we get here
}